/* Style: ورق المدرسة المعاصر — تعليمات RTL عملية، خط زمني مرئي، وحذر أمني هادئ لا يربك الولي. */
import { ArrowRight, CheckCircle2, ChevronDown, Download, HelpCircle, LockKeyhole, ShieldCheck, Smartphone } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

const APK_URL = "https://github.com/nadjimyahiaoui1992-lab/quratie/releases/download/v1.0.0/app-release.apk";

const details = [
  ["هل التطبيق من Google Play؟", "لا. هذه نسخة APK رسمية منشورة من مستودع Qiraati، لذلك سيطلب Android تأكيد التثبيت من مصدر خارج المتجر."],
  ["هل أحتاج إلى حساب؟", "لا تحتاج إلى حساب لتنزيل الملف. بعد التثبيت يمكنك فتح التطبيق والبدء بإضافة ملف التلميذ."],
  ["كيف أحصل على التحديثات؟", "يتحقق التطبيق من وجود إصدار أحدث، وعند توفره يظهر لك رابط التنزيل الرسمي من صفحة GitHub Releases."],
];

export default function Install() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <main dir="rtl" className="min-h-screen bg-[#f7f3eb] text-[#142b3d]">
      <header className="border-b border-[#dfe7df] bg-[#fffdf8]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#142b3d] p-2"><img src="assets/qiraati-mark.png" alt="" className="h-full w-full object-contain" /></span><span className="font-display text-lg font-extrabold">Qiraati</span></Link><Link href="/" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#0b8d6a]"><ArrowRight className="h-4 w-4" /> العودة للصفحة الرئيسية</Link></div></header>
      <section className="mx-auto max-w-6xl px-5 pb-16 pt-16 lg:px-10 lg:pt-24"><div className="max-w-3xl"><p className="mb-4 text-sm font-black text-[#0b8d6a]">دليل التثبيت الرسمي</p><h1 className="font-display text-5xl font-black leading-[1.15] tracking-[-.04em] sm:text-6xl">ثبّت Qiraati<br /><span className="text-[#0b8d6a]">بخطوات واضحة.</span></h1><p className="mt-6 max-w-2xl text-lg leading-9 text-[#61707a]">هذه التعليمات مخصصة لتثبيت ملف APK على هاتف Android عندما يكون التطبيق خارج متجر Google Play.</p></div></section>
      <section className="mx-auto grid max-w-6xl gap-8 px-5 pb-20 lg:grid-cols-[1fr_.8fr] lg:px-10"><div className="rounded-[2rem] bg-[#142b3d] p-7 text-white sm:p-10"><div className="mb-10 flex items-center justify-between"><div><p className="text-sm font-black text-[#62c7a4]">النسخة الحالية</p><h2 className="mt-2 font-display text-3xl font-black">Qiraati v1.0.0</h2></div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-white/10"><Download className="h-6 w-6 text-[#62c7a4]" /></div></div><p className="max-w-md text-sm leading-7 text-white/65">ملف Release موقّع، مخصص لأجهزة Android، بحجم يقارب 20.7 MB.</p><a href={APK_URL} className="mt-8 inline-flex items-center gap-3 rounded-xl bg-[#62c7a4] px-6 py-4 font-extrabold text-[#102b38] transition duration-200 hover:-translate-y-1 active:scale-[.97]"><Download className="h-5 w-5" /> تنزيل ملف APK</a></div><div className="rounded-[2rem] border border-[#dfe7df] bg-[#fffdf8] p-7 sm:p-10"><div className="flex items-start gap-4"><LockKeyhole className="mt-1 h-6 w-6 shrink-0 text-[#0b8d6a]" /><div><h2 className="font-display text-xl font-extrabold">قبل أن تبدأ</h2><p className="mt-3 text-sm leading-7 text-[#61707a]">نزّل الملف من الرابط الرسمي فقط، وتأكد أن اسم الملف هو `app-release.apk`. لا تثبّت نسخًا مرسلة من مصادر غير معروفة.</p></div></div></div></section>
      <section className="border-y border-[#dfe7df] bg-[#fffdf8] px-5 py-20 lg:px-10"><div className="mx-auto max-w-6xl"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-sm font-black text-[#0b8d6a]">المسار الكامل</p><h2 className="font-display text-4xl font-black">ثلاث خطوات قصيرة.</h2></div><span className="inline-flex items-center gap-2 text-sm font-bold text-[#70808a]"><Smartphone className="h-4 w-4" /> Android 8.0 أو أحدث</span></div><div className="grid gap-8 md:grid-cols-3">{[{n:"01",title:"نزّل الملف",body:"اضغط على زر تنزيل ملف APK، ثم انتظر اكتمال التنزيل في مجلد Downloads."},{n:"02",title:"اسمح لهذا المصدر",body:"افتح الملف. إذا ظهر تحذير، افتح إعدادات السماح للمتصفح وفعّل التثبيت من هذا المصدر."},{n:"03",title:"ثبّت وافتح",body:"ارجع إلى الملف واضغط تثبيت. بعد الانتهاء، افتح Qiraati وابدأ بإضافة ملف التلميذ."}].map((step, i) => <article key={step.n} className="relative border-t-2 border-[#62c7a4] pt-6"><span className="font-display text-sm font-black text-[#e2a92d]">{step.n}</span><h3 className="mt-6 font-display text-2xl font-extrabold">{step.title}</h3><p className="mt-3 text-sm leading-7 text-[#61707a]">{step.body}</p>{i < 2 && <div className="absolute -left-5 top-[-9px] hidden h-4 w-4 rounded-full bg-[#62c7a4] md:block" />}</article>)}</div></div></section>
      <section className="mx-auto max-w-4xl px-5 py-20 lg:px-10"><div className="mb-10 flex items-center gap-3"><HelpCircle className="h-6 w-6 text-[#0b8d6a]" /><h2 className="font-display text-3xl font-black">أسئلة شائعة</h2></div><div className="divide-y divide-[#dfe7df] rounded-[1.5rem] border border-[#dfe7df] bg-[#fffdf8] px-6">{details.map(([q,a], i) => <div key={q} className="py-5"><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-4 text-right font-extrabold"><span>{q}</span><ChevronDown className={`h-5 w-5 shrink-0 text-[#0b8d6a] transition-transform duration-200 ${open === i ? "rotate-180" : ""}`} /></button>{open === i && <p className="mt-4 max-w-2xl text-sm leading-7 text-[#61707a]">{a}</p>}</div>)}</div></section>
      <section className="border-t border-[#dfe7df] bg-[#e6efe7] px-5 py-14 lg:px-10"><div className="mx-auto flex max-w-6xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-[#0b8d6a]" /><p className="max-w-xl text-sm font-semibold leading-7 text-[#31505d]">بعد التثبيت، يمكنك إيقاف السماح بالتثبيت من المصادر غير المعروفة. لا تشارك ملف APK أو رابطًا غير رسمي.</p></div><Link href="/" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#0b8d6a]">العودة للتنزيل <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main>
  );
}
