/* Style: ورق المدرسة المعاصر — سياسة خصوصية عربية واضحة، طبقات قصيرة، وهوامش تحريرية تشبه دليلًا مدرسيًا موثوقًا. */
import { ArrowRight, ExternalLink, LockKeyhole, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function Privacy() {
  return (
    <main dir="rtl" className="paper-page min-h-screen bg-[#f7f3eb] text-[#142b3d]">
      <header className="border-b border-[#dfe7df] bg-[#fffdf8]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#142b3d] p-2"><img src="assets/qiraati-mark.png" alt="" className="h-full w-full object-contain" /></span><span className="font-display text-lg font-extrabold">Qiraati</span></Link><Link href="/" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#0b8d6a]"><ArrowRight className="h-4 w-4" /> العودة إلى التنزيل</Link></div></header>
      <section className="mx-auto max-w-4xl px-5 pb-16 pt-16 lg:px-10 lg:pt-24"><span className="stamp">آخر تحديث · 21 أوت 2026</span><h1 className="mt-6 font-display text-5xl font-black leading-tight sm:text-6xl">سياسة الخصوصية</h1><p className="mt-6 max-w-2xl text-lg leading-9 text-[#61707a]">نشرح هنا، بلغة واضحة، ما يحدث لبيانات الولي والتلميذ عند استعمال تطبيق Qiraati وصفحة التنزيل.</p></section>
      <section className="mx-auto grid max-w-4xl gap-5 px-5 pb-16 lg:grid-cols-2 lg:px-10"><div className="rounded-[1.7rem] bg-[#142b3d] p-7 text-white"><ShieldCheck className="h-7 w-7 text-[#62c7a4]" /><h2 className="mt-7 font-display text-2xl font-black">مبدأنا</h2><p className="mt-3 text-sm leading-7 text-white/70">نجمع أقل قدر ممكن من البيانات، ونستخدمها فقط لتشغيل ميزات التطبيق وتحسين التجربة.</p></div><div className="rounded-[1.7rem] border border-[#dfe7df] bg-[#fffdf8] p-7"><LockKeyhole className="h-7 w-7 text-[#0b8d6a]" /><h2 className="mt-7 font-display text-2xl font-black">حماية القُصّر</h2><p className="mt-3 text-sm leading-7 text-[#61707a]">التطبيق موجّه للولي والتلميذ، ويجب أن يدير الولي إدخال بيانات التلميذ ومراجعتها.</p></div></section>
      <article className="mx-auto max-w-4xl space-y-10 px-5 pb-24 lg:px-10">
        <section><h2 className="font-display text-2xl font-black">1. البيانات التي قد تُحفظ</h2><p className="mt-3 text-base leading-8 text-[#52636d]">قد يحفظ التطبيق بيانات ملف التلميذ التي يدخلها الولي، مثل الاسم أو المستوى أو الشعبة، إضافة إلى الجدول والمهام والتنبيهات التي يختار المستخدم تسجيلها. لا نطلب هذه البيانات من أجل الإعلانات ولا نبيعها.</p></section>
        <section><h2 className="font-display text-2xl font-black">2. الكاميرا والجدول</h2><p className="mt-3 text-base leading-8 text-[#52636d]">عند استعمال تصوير الجدول، يطلب Android صلاحية الكاميرا. تُستخدم الكاميرا لهذه الوظيفة فقط، ويجب أن يختار الولي الصور والملفات التي يريد إدخالها. لا تمنح التطبيق صلاحية الوصول العام إلى ملفات الهاتف خارج ما يختاره المستخدم.</p></section>
        <section><h2 className="font-display text-2xl font-black">3. Firebase وGemini</h2><p className="mt-3 text-base leading-8 text-[#52636d]">قد يستخدم التطبيق خدمات Firebase لبعض وظائف البنية والتوزيع. ميزات الذكاء الاصطناعي لا تضع مفتاح Gemini داخل التطبيق؛ تمر الطلبات عبر وسيط خادمي مخصص. لا ترسل معلومات حساسة عن الطفل إلى الذكاء الاصطناعي إلا بعد مراجعة الولي للمحتوى.</p></section>
        <section><h2 className="font-display text-2xl font-black">4. الإشعارات</h2><p className="mt-3 text-base leading-8 text-[#52636d]">يمكن للتطبيق إنشاء إشعارات محلية حول المهام اليومية. يستطيع المستخدم رفض صلاحية الإشعارات أو إيقافها من إعدادات Android دون منع استعمال الوظائف الأساسية.</p></section>
        <section><h2 className="font-display text-2xl font-black">5. حقوق الولي</h2><p className="mt-3 text-base leading-8 text-[#52636d]">يمكن للولي مراجعة البيانات المحفوظة داخل التطبيق أو تعديلها أو حذف ملف التلميذ من الجهاز. لطلب مساعدة بخصوص الخصوصية أو حذف بيانات مرتبطة بخدمة خارجية، تواصل معنا عبر قناة الدعم الرسمية.</p></section>
        <section className="rounded-[1.7rem] border border-[#d5e4d9] bg-[#e6efe7] p-7"><h2 className="font-display text-2xl font-black">التواصل</h2><p className="mt-3 text-sm leading-7 text-[#52636d]">للاستفسارات المتعلقة بالخصوصية أو التثبيت، استخدم صفحة الإصدار الرسمية أو افتح مستودع Qiraati على GitHub.</p><a href="https://github.com/nadjimlab/quratie" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 font-extrabold text-[#0b8d6a]">مستودع Qiraati <ExternalLink className="h-4 w-4" /></a></section>
      </article>
    </main>
  );
}
